remote_theme: pages-themes/cayman@v0.2.0
title: "Guide complet du Wind Knight (spec Skyward)"
plugins:
- jekyll-remote-theme

github:
  is_project_page: true
  repository_url: https://https://github.com/MrDustyBowl/mrdustybowl.github.io
